# Refer https://adamj.eu/tech/2023/11/02/github-actions-faster-python-virtual-environments/ for more details
name: Python-Build-With-Cache
on:
  - push
  - workflow_dispatch

env:
  KEY: ""

jobs:
  python_build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Compute key for cache
        run: |
          # The key would be venv-ubuntu-3.23-<ShaIdOfRequirementsTxtFileGoesHere>
          echo "KEY=venv-$RUNNER_OS-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}" >> $GITHUB_ENV 
      - name: Restore cached virtualenv # Try restoring from cache if it's available
        uses: actions/cache/restore@v4
        with:
          key: KEY
          # Cache the .venv directory
          path: .venv
      - name: setup dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
      - name: Saved cached virtualenv
        uses: actions/cache/save@v4
        with:
          key: KEY
          path: .venv
