name: Caching-Experiments-Using-Composite-Actions

on:
  workflow_dispatch:

env:
  version: 2.30.0

permissions:
  contents: write

jobs:
  implement-caching:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Test
        if: always()
        run: pytest --alluredir=allure-results tests/allure_sample_test.py
        continue-on-error: true

      - name: Generate and publish allure reports
        uses: ./.github/custom-actions/generate-publish-allure-reports
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


