name: Run CI for python tests

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Setup virtual environment
      run: python -m venv .venv
    - name: Init virtual environment
      run: source .venv/bin/activate
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Resolve dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest -s --pythonpath=. --html=results/report.html --self-contained-html
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: warn
        name: pytest-test-results
        artifact-id: pytest-test-results
        path: results/

